id: ID1B14DC6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T12:18:19+00:00'
last_modified: '2022-06-07T12:14:36.091413+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG04059
  title: རི་བོ་དགེ་ལྡན་པའི་ཆོས་སྤྱོད་ཁག་གཅིག་གི་འགྲེལ་བ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    2F94:
      image_group_id: I00KG04075
      title: Volume 1 of ri bo dge ldan pa'i chos spyod khag gcig gi 'grel ba
      total_pages: 202
      order: 1
      base_file: 2F94.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
